### ISSUE TITLE
Resolution Tag on small LED Screens

### ISSUE THREAD

**Issue by Lagges** [theexperiential/Artio#1]
When working with LED Screens that are only one Module in height (128), you can't see the resolution on the screens any longer. It would be nice, to have separate transform parameters  for each of the texts.

_+1 for the screen rotation you mentioned in your video._ 

_But Arito is really awesome and will definitely come in handy in the future._

**Comment by dylanroscover** [comment]
Good catch @Lagges ... yeah, that whole Text/Logo module definitely wasn't working well with lower resolutions at all. I just pushed v0.3.5 which fixes a bunch of things with that, and has better scaling of text/logo/corner elements in general.

Thanks so much for pointing out this issue!

FYI screen rotation has been added to Artio - let me know what you think of how that works / if it's intuitive enough.

**Comment by Lagges** [comment]
Works great now.

The screen rotation works just as i would expect.

Thanks for your great work.
